version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  target-branch: release/3.x
  ignore:
  - dependency-name: com.diffplug.gradle.spotless
    versions:
    - 5.10.0
    - 5.10.1
    - 5.10.2
    - 5.11.0
    - 5.11.1
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.9.0
  - dependency-name: org.eclipse.platform:org.eclipse.osgi
    versions:
    - 3.16.100
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - 1.4.2-native-mt
  - dependency-name: biz.aQute.bnd.builder
    versions:
    - 5.2.0
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: org.objenesis:objenesis
    versions:
    - "3.1"
  - dependency-name: com.google.auto.service:auto-service
    versions:
    - 1.0-rc7
